### ISSUE TITLE
CREATE_FAILED | AWS::S3::Bucket | documentuploadbucket1B3E1E18

### ISSUE THREAD

**Issue by jeremieca** [aws-samples/amazon-s3-multipart-upload-transfer-acceleration#16]
Hi !

I just cloned the repo and attempted to deploy, but encountered an error.

I followed the documentation to deploy the backendV2. During the cdk deploy command, I encountered a peculiar error with a null message and an "AlreadyExists" error. This is perplexing to me because I don't have any buckets in my project except the one from cdk bootstrap.

It's unclear to me how it's supposed to work, and I'm struggling to understand why there seems to have capital letters in the bucket name "documentuploadbucket1B3E1E18". Is that the error ?

<img width="1089" alt="image" src="https://github.com/aws-samples/amazon-s3-multipart-upload-transfer-acceleration/assets/2277218/5c8a8282-c85c-49ca-97c9-a3127ca7ea87">

Thank you for your coming help !

**Comment by akomandooru** [comment]
If you look at the constructor code of the MultipartS3UploadStack, you will see the bucketName: `document-client-upload-${env}` where the last part of the name comes from the env context variable you used during deployment. This code is making a unique bucket name but it possible to have a collision; in that case, you need to try using a different random number or change the code to use a unique bucket name. 
Make sure you are using the source from the sample and provide a random number in string format to the deployment command line; also, check the bucket naming rules at https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

**Comment by jeremieca** [comment]
I correctly defined context. In my previous message I though documentuploadbucket1B3E1E18 was the bucket name, it's not according to this screenshot :

<img width="971" alt="image" src="https://github.com/aws-samples/amazon-s3-multipart-upload-transfer-acceleration/assets/2277218/a023c8ff-7661-46e5-9b87-a5654b3a30b7">

Still have the error.
Again, my aws account is clean, it's a new one. So no collision is possible.

Any other idea ?

**Comment by akomandooru** [comment]
If you look at the bucket naming rules link I shared in the previous message, you will see "Bucket names must be unique across all AWS accounts in all the AWS Regions within a partition." 

The error message is saying "AlreadyExists". Can you generate a 6 or 7 digit random number in your tool of choice and use it for the env context variable?

**Comment by jeremieca** [comment]
Ok ! Across all aws account! I understand now.

I missread sorry.
