### ISSUE TITLE
Unable to access API gateway - 403 forbidden

### ISSUE THREAD

**Issue by mok419** [aws-samples/amazon-s3-multipart-upload-transfer-acceleration#19]
I succesfully deployed the the cloudformation using this statement:
cdk deploy --context env="9189086" --context whitelistip="0.0.0.0"

every time I call the initialize, I get forbidden 403 for the CORS options call.

I checked the resource policy and saw that deny requests from any IP 0.0.0.0 which is bad, so I removed the deny section completely.

I'm trying to test it locally, but can't get past this 403 for initialize OPTIONs call
<img width="722" alt="image" src="https://github.com/aws-samples/amazon-s3-multipart-upload-transfer-acceleration/assets/135124328/c303400a-f158-4296-a81e-a90e49db30a1">

**Comment by mok419** [comment]
I changed the resource policy to this:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": "*",
      "Action": "execute-api:Invoke",
      "Resource": "arn:aws:execute-api:us-east-1:590183769630:1z14m6zgql/*/*/*"
    }
  ]
}

which should allow anyone to access, but I am getting same issue saying I am not authorised although Prinipal * should allow any user to access?
https://repost.aws/knowledge-center/api-gateway-troubleshoot-403-forbidden

**Comment by akomandooru** [comment]
For the whitelistip context variable, it is expected to use your client IP address - you can get yours by using a tool like https://whatismyipaddress.com/

Can you try using your IP address in the whitelist and share your results?

**Comment by mok419** [comment]
Legend, many thanks that worked a charm!

Not sure why removing deny didn't solve it (but am happy anyway!)
